In [1]:
import numpy as np

In [9]:
# 1 d array
a = np.array([1,2,3,4,5])
print(a)
type(a)

[1 2 3 4 5]


numpy.ndarray

In [11]:
# 2d array

b = np.array([[1,2,3],[4,5,6]])
print(b)
type(b)

[[1 2 3]
 [4 5 6]]


numpy.ndarray

In [15]:
# 3 d array 

c = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]]) 
print(c)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [17]:
a= np.array([1,2,3,4,5],dtype='float32')
print(a)

[1. 2. 3. 4. 5.]


In [18]:
b= np.array([[1,2,3],[4,5,6]],dtype='int32')
print(b)

[[1 2 3]
 [4 5 6]]


In [20]:
c=np.array([1,2,3],dtype=bool)
print(c)

[ True  True  True]


In [21]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(1,100)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [23]:
np.arange(1,100,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [29]:
np.arange(0,100).reshape(10,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [30]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [32]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [33]:
np.random.rand(3,4)


array([[0.61447369, 0.43571379, 0.20846581, 0.41047607],
       [0.58260261, 0.21679046, 0.81416066, 0.82425171],
       [0.24162858, 0.61805277, 0.7285605 , 0.1885405 ]])

In [34]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [ ]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [36]:
np.identity(199)

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]], shape=(199, 199))

In [2]:
import numpy as  np

In [13]:
a1=np.array([1,2,3,4,5])
a2=np.array([[1,2,3],
            [4,5,6]])
a3=np.array([[[1,2,3],
            [4,5,6],
            [7,8,9]]])



In [23]:
print(a1)
print(a2)
print(a3)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]
[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [9]:
a1.ndim

1

In [10]:
a2.ndim

2

In [11]:
a3.ndim

3

In [12]:
a1.size

5

In [14]:
a2.size

6

In [15]:
a3.size

9

In [16]:
a1.itemsize

8

In [17]:
a2.itemsize

8

In [18]:
a3.itemsize

8

In [19]:
a1.shape

(5,)

In [20]:
a2.shape

(2, 3)

In [21]:
a3.shape

(1, 3, 3)

In [22]:
a3.astype('int32')

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]], dtype=int32)

In [24]:
a1=np.arange(12).reshape(3,4)
a2=np.arange(12,24).reshape(3,4)

In [25]:
a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [26]:
a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [31]:
a1 

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [32]:
a1>5

array([[False, False, False, False],
       [False, False,  True,  True],
       [ True,  True,  True,  True]])

In [33]:
a1==3

array([[False, False, False,  True],
       [False, False, False, False],
       [False, False, False, False]])

In [34]:
a1+a2

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [35]:
a1*a2

array([[  0,  13,  28,  45],
       [ 64,  85, 108, 133],
       [160, 189, 220, 253]])

In [36]:
a1/a2

array([[0.        , 0.07692308, 0.14285714, 0.2       ],
       [0.25      , 0.29411765, 0.33333333, 0.36842105],
       [0.4       , 0.42857143, 0.45454545, 0.47826087]])

In [38]:
a1 = np.random.rand(3,4)
a1

array([[0.96318318, 0.47310122, 0.85274368, 0.26945607],
       [0.66637172, 0.68273052, 0.70593813, 0.12513644],
       [0.58070238, 0.06291271, 0.47677806, 0.39217617]])

In [44]:
a1

array([[10.,  5.,  9.,  3.],
       [ 7.,  7.,  7.,  1.],
       [ 6.,  1.,  5.,  4.]])

In [42]:
np.max(a1)

np.float64(10.0)

In [45]:
a3=np.array([[[1,2,3],
            [4,5,6],
            [7,8,9]]])

In [46]:
a3

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [48]:
# 0 -> column , 1 -> 

np.max(a1,axis=0)

array([10.,  7.,  9.,  4.])

In [49]:
np.mean(a1)

np.float64(5.416666666666667)

In [50]:
np.min(a3)

np.int64(1)

In [51]:
np.mean(a1)

np.float64(5.416666666666667)

In [52]:
np.sin(a1)

array([[-0.54402111, -0.95892427,  0.41211849,  0.14112001],
       [ 0.6569866 ,  0.6569866 ,  0.6569866 ,  0.84147098],
       [-0.2794155 ,  0.84147098, -0.95892427, -0.7568025 ]])

In [53]:
a2=np.arange(12).reshape(3,4)
a3=np.arange(12,24).reshape(4,3)

In [56]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [57]:
a3

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [54]:
np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [59]:
np.log(a1)

array([[2.30258509, 1.60943791, 2.19722458, 1.09861229],
       [1.94591015, 1.94591015, 1.94591015, 0.        ],
       [1.79175947, 0.        , 1.60943791, 1.38629436]])

In [60]:
np.exp(a1)

array([[2.20264658e+04, 1.48413159e+02, 8.10308393e+03, 2.00855369e+01],
       [1.09663316e+03, 1.09663316e+03, 1.09663316e+03, 2.71828183e+00],
       [4.03428793e+02, 2.71828183e+00, 1.48413159e+02, 5.45981500e+01]])

In [62]:
np.round(np.random.random((2,3))*100)

array([[72., 79.,  5.],
       [55.,  3., 77.]])